name: diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: 'docs/assets/repo-structure-diagram.svg'
          excluded_paths: '.github,.vscode'
